name: integrate
on:
  push:
    branches:
      - "renovate/**"
      - "testing/**"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    name: "Node 14"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1
      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}
      ##################################################
      #   _           _ _     _
      #  | |__  _   _(_) | __| |
      #  | '_ \| | | | | |/ _` |
      #  | |_) | |_| | | | (_| |
      #  |_.__/ \__,_|_|_|\__,_|
      ##################################################
      - name: build
        run: |
          npm ci
          npm run lint
          npm run test
          npm run build

      ###################################################
      ##   _ __  _ __  _ __ ___
      ##  | '_ \| '_ \| '_ ` _ \
      ##  | | | | |_) | | | | | |
      ##  |_| |_| .__/|_| |_| |_|
      ##        |_|
      ###################################################
      - name: npm-publish-dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --dry-run
      ###################################################
      ##    __                        ___.          .__  .__
      ## _/  |______ _______         \_ |__ _____  |  | |  |
      ## \   __\__  \\_  __ \  ______ | __ \\__  \ |  | |  |
      ## |  |  / __ \|  | \/ /_____/ | \_\ \/ __ \|  |_|  |__
      ## |__| (____  /__|            |___  (____  /____/____/
      ##           \/                    \/     \/
      ###################################################
      - name: create-local-npm-tar-ball
        run: npm pack
      - name: create-tar-ball-artifact
        uses: actions/upload-artifact@v2
        with:
          name: gvhinks-fastify-cookie-monster-tar-ball
          path: "gvhinks-fastify-cookie-monster-${{ steps.extract_version.outputs.version }}.tgz"

      ##################################################
      #
      # note the github docker registry requires the docker
      # repository to be :user/:repo_name/image_name
      # The registry is the internal github docker registry
      #
      ##################################################
      - name: docker-build-publish-fastify-server-to-github-registry
        uses: docker/build-push-action@v2
        with:
          context: .
          username: ${{ secrets.ACTIONS_GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ secrets.ACTIONS_GITHUB_USERNAME }}/fastify-cookie-monster
          registry: docker.pkg.github.com
          tags: latest
          file: Dockerfile.integration
          push: true
