name: integrate
on:
  push:
    branches:
      - "renovate/**"
      - "testing/**"
  workflow_dispatch:
jobs:
  ##################################################
  #    _____           _                                   _     _
  #   |_   _|         | |                                 | |   (_)
  #     | |    _ __   | |_    ___    __ _   _ __    __ _  | |_   _    ___    _ __
  #     | |   | '_ \  | __|  / _ \  / _` | | '__|  / _` | | __| | |  / _ \  | '_ \
  #    _| |_  | | | | | |_  |  __/ | (_| | | |    | (_| | | |_  | | | (_) | | | | |
  #   |_____| |_| |_|  \__|  \___|  \__, | |_|     \__,_|  \__| |_|  \___/  |_| |_|
  #                                  __/ |
  #                                 |___/
  #
  ##################################################
  integration-fastify:
    runs-on: ubuntu-latest
    services:
      fastify:
        image: ghinks/fastify-cookie-monster-store
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: npm ci
      - name: curl-route-hit
        run: curl 127.0.0.1:3000 --verbose -m 50 --connect-timeout 100
      - name: integration-test-suite
        run: ./node_modules/.bin/tap integration/tests/smoke.tests.ts
