name: integrate
on:
  push:
    branches:
      - "renovate/**"
      - "testing/**"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    name: "Node 14"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1
      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}
      ##################################################
      #   _           _ _     _
      #  | |__  _   _(_) | __| |
      #  | '_ \| | | | | |/ _` |
      #  | |_) | |_| | | | (_| |
      #  |_.__/ \__,_|_|_|\__,_|
      ##################################################
      - name: build
        run: |
          npm ci
          npm run lint
          npm run test
          npm run build

      ###################################################
      ##   _ __  _ __  _ __ ___
      ##  | '_ \| '_ \| '_ ` _ \
      ##  | | | | |_) | | | | | |
      ##  |_| |_| .__/|_| |_| |_|
      ##        |_|
      ###################################################
      - name: npm-publish-dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --dry-run
      ###################################################
      ##    __                        ___.          .__  .__
      ## _/  |______ _______         \_ |__ _____  |  | |  |
      ## \   __\__  \\_  __ \  ______ | __ \\__  \ |  | |  |
      ## |  |  / __ \|  | \/ /_____/ | \_\ \/ __ \|  |_|  |__
      ## |__| (____  /__|            |___  (____  /____/____/
      ##           \/                    \/     \/
      ###################################################
      - name: create-local-npm-tar-ball
        run: npm pack
      - name: create-tar-ball-artifact
        uses: actions/upload-artifact@v2
        with:
          name: gvhinks-fastify-cookie-monster-tar-ball
          path: "gvhinks-fastify-cookie-monster-${{ steps.extract_version.outputs.version }}.tgz"

      ##################################################
      #
      #  The default registry is the docker public registry
      #  however for the purposes of comparison the author
      #  has included the registry so that the step is
      #  easier to compare to the publish to the github
      # docker registry
      #
      ##################################################
      - name: docker-build-publish-fastify-server-to-docker-registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.GIT_ACTIONS_DOCKER_USERNAME }}
          password: ${{ secrets.GIT_ACTIONS_FASTIFY_COOKIE_MONSTER }}
          repository: ${{ secrets.GIT_ACTIONS_DOCKER_USERNAME }}/fastify-cookie-monster-store
          registry: registry.hub.docker.com
          tags: latest
          dockerfile: Dockerfile.integration
      ##################################################
      #
      # note the github docker registry requires the docker
      # repository to be :user/:repo_name/image_name
      # The registry is the internal github docker registry
      #
      ##################################################
      #      - name: docker-build-publish-fastify-server-to-github-registry
      #        uses: docker/build-push-action@v2
      #        with:
      #          context: .
      #          tags: latest
      #          file: Dockerfile.integration
      #          push: true
      - name: docker-build-publish-fastify-server-to-github-registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ghinks/fastify-cookie-monster/fastify-cookie-monster-store
          registry: docker.pkg.github.com
          tags: latest
          dockerfile: Dockerfile.integration
  integration-fastify:
    needs: publish
    runs-on: ubuntu-latest
    services:
      fastify:
        image: ghinks/fastify-cookie-monster-store
        ports:
          - 3000:3000
    steps:
      - name: curl-route-hit
        run: curl 127.0.0.1:3000 --verbose -m 5 --connect-timeout 10
